version: "3.7"

services:
  gen-signed-cert:
    container_name: gen-signed-cert
    image: lchaia/gen-signed-cert
    build:
      context: ./src
    environment:
      SSL_SUBJECT: lchaia.astonishinglabs.net
    volumes:
      - ./certs:/certs
